# Generated by Django 4.1.7 on 2023-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gst_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Gst'),
        ),
    ]
