# Generated by Django 4.1.7 on 2023-03-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_category_gst_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gst_tax',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Gst'),
        ),
    ]
